### ISSUE TITLE
Cannot set properties of undefined (setting 'getAsVal')

### ISSUE THREAD

**Issue by yellowimg** [sscfaith/avue-form-design#80]
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'getAsVal')
    at Object.install (index.umd.min.js:formatted:90337:NaN)
    at Object.use (runtime-core.esm-bundler.js:4327:28)
    at bootstrap (main.ts:58:7)

下面是我全局引用方法
import  AvueFormDesign  from '@sscfaith/avue-form-design';
async function bootstrap() {
  const app = createApp(App);
  app.use(AvueFormDesign).mount('#app');
}

**Comment by yellowimg** [comment]
使用vue3 , avue:3.1.0 ,ts ,element-plus:2.2.12,@sscfaith/avue-form-design:1.5.6
